### PR TITLE
Feature/gha release

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #28

### CODE REVIEW

**Comment by CAMOBAP** [comment]
I will enable logs on CI because locally it works without any issues

**Comment by CAMOBAP** [comment]
```
...
2021-12-24T17:03:52.5432220Z error: There is no XCFramework found at '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20211224-1966-atnk4x/Carthage/Checkouts/HCaptcha-ios-sdk/Carthage/Build/RxSwift.xcframework'. (in target 'HCaptcha_RxSwift' from project 'HCaptcha-Carthage')
```

Also reproduced this issue locally, for some reason Fastlane exits with 0 on my machine

**Comment by CAMOBAP** [comment]
It looks like a known issue https://github.com/Carthage/Carthage/issues/3243

It doesn't reproduce for 5.1.3, but reproduces for 6.2.0, checking RxSwift diff

**Comment by CAMOBAP** [comment]
@e271828- ready for review

**Review by e271828- — APPROVED** [review]

**Pull request merged**
