### PR TITLE
Bump to 1.7.0

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #29

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@e271828- I have concerns about those lines https://github.com/hCaptcha/HCaptcha-ios-sdk/blob/master/fastlane/Fastfile#L129-L131

`Carthage` doesn't support archive for `xcframework`, so this step may failues

Let me doublecheck this

**Comment by CAMOBAP** [comment]
> @e271828- I have concerns about those lines https://github.com/hCaptcha/HCaptcha-ios-sdk/blob/master/fastlane/Fastfile#L129-L131
> 
> `Carthage` doesn't support archive for `xcframework`, so this step may failues
> 
> Let me doublecheck this

Yep it will(

```
[22:33:24]: Exit status of command 'carthage archive' was 1 instead of 0.
Could not find any copies of HCaptcha.framework, HCaptcha_RxSwift.framework. Make sure you're in the project's root and that the frameworks have already been built using 'carthage build --no-skip-current'.
```

Let me explain, `Carthage` will work even without `"HCaptcha.framework.zip"` uploaded. This upload will just save a build time for the end-users. We are using `--use-xcframeworks` because it will fail link with `RxSwift` I didn't researched this issue deeper

Here we have two options:
1. Investigate why do we use `--use-xcframeworks`, can we build a regular `framework`?
2. Skip `"HCaptcha.framework.zip"` upload, anyway because of https://github.com/Carthage/Carthage/issues/3243 end users forced to pass `--no-use-binaries`, and drop prebuilts

@e271828- how do you think?

**Comment by e271828-** [comment]
> > @e271828- I have concerns about those lines https://github.com/hCaptcha/HCaptcha-ios-sdk/blob/master/fastlane/Fastfile#L129-L131
> > `Carthage` doesn't support archive for `xcframework`, so this step may failues
> > Let me doublecheck this
> 
> Yep it will(
> 
> ```
> [22:33:24]: Exit status of command 'carthage archive' was 1 instead of 0.
> Could not find any copies of HCaptcha.framework, HCaptcha_RxSwift.framework. Make sure you're in the project's root and that the frameworks have already been built using 'carthage build --no-skip-current'.
> ```
> 
> Let me explain, `Carthage` will work even without `"HCaptcha.framework.zip"` uploaded. This upload will just save a build time for the end-users. We are using `--use-xcframeworks` because it will fail link with `RxSwift` I didn't researched this issue deeper
> 
> Here we have two options:
> 
> 1. Investigate why do we use `--use-xcframeworks`, can we build a regular `framework`?
> 2. Skip `"HCaptcha.framework.zip"` upload, anyway because of [Carthage build produces random results with RxSwift Carthage/Carthage#3243](https://github.com/Carthage/Carthage/issues/3243) end users forced to pass `--no-use-binaries`, and drop prebuilts
> 
> @e271828- how do you think?

`XCFramework` is the future, so I'd like to stick with it.

I don't think Carthage is that popular, so probably option 2 is the best.

**Comment by CAMOBAP** [comment]
@e271828- PR updated:
 - README.md (objc and carthage issues)
 - timeout increased

**Review by e271828- — APPROVED** [review]

**Pull request merged**
